# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('reviews', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reviewword',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Review'),
        ),
        migrations.AddField(
            model_name='reviewword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
        migrations.AddField(
            model_name='review',
            name='words',
            field=models.ManyToManyField(through='words.ReviewWord', to='words.Word'),
        ),
    ]
