# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20180324_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='nickname',
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
