# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180324_1741'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='word',
            managers=[
                ('words', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
