# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_review_words_analyzed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='words',
            field=models.ManyToManyField(blank=True, through='words.ReviewWord', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='reviewword',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
    ]
